CONFIG = {
    "COMPANY_NAME": "Apple Inc.",
    "TICKET_STATUSES": ["Pending", "Approved", "Rejected"],
    "TICKET_GROUPS": {
        "ITEMS": [
            "KEYBOARD",
            "MOUSE",
            "LAPTOP ISSUE",
            "CHARGER",
            "HEADSET",
            "RAM CHANGE",
            "SCREEN ISSUE",
            "KEYPAD ISSUE",
            "TOUCHPAD ISSUE",
        ],
        "ACCESS": ["VPN ACCESS", "EMAIL ACCESS", "BIOMETRIC ACCESS"],
        "ISSUES": ["SOFTWARE ISSUE", "NETWORK ISSUE", "PERFORMANCE ISSUE"],
        "OTHER": ["OTHER"],
    },
    "SERVICE_REQUEST_TYPES": {
        "DevOps": ["Add Port", "Add VPN", "Add Route", "Add Firewall"],
        "Developer": ["GitHub Access Request"],
    },
    "LABELS": {
        "SIDEBAR_SECTION_ADMIN": "Admin",
        "SIDEBAR_SECTION_EMPLOYEE": "Employee",
        "NAV_DASHBOARD": "Dashboard",
        "NAV_EMPLOYEES": "Employees",
        "NAV_MANAGE": "Manage",
        "NAV_USER_MANAGEMENT": "User Management",
        "NAV_TICKETS": "Tickets",
        "NAV_SERVICE_REQUESTS": "Service Requests",
        "NAV_GITHUB_ACCESS": "GitHub Access",
        "NAV_MY_DETAILS": "My Details",
        "NAV_RAISE_TICKET": "Raise Ticket",
        "NAV_SIGN_OUT": "Sign Out",
        "LOGIN_SUBTITLE": "Sign in to continue to your workspace",
    },
    "USERS": [
        {
            "name": "Admin",
            "email": "admin@apple.com",
            "phone": "1234567890",
            "department": "Administration",
            "Admin": True,
            "password": "Admin@123",
            "assets": {
                "laptop": "MBP001",
                "charger": "CRR001",
                "keyboard": "KB001",
                "mouse": "MUE001",
                "headset": "HS001",
            },
        },
        {
            "name": "Aparna",
            "email": "aparna@apple.com",
            "phone": "1234567890",
            "department": "Human Resources",
            "password": "Aparna@123",
            "assets": {
                "laptop": "MBP002",
                "charger": "CRR002",
                "keyboard": "KB002",
                "mouse": "MUE002",
                "headset": "HS002",
            },
        },
    ],
}